### ISSUE TITLE
Changes in STEP4to5-VISIT_OCCURRENCE.v10.16_05_2021.Rmd line 51

### ISSUE THREAD

**Issue by DanOV** [UMC-Utrecht-RWE/ConcePTION-Level1#4]
We had the following error in VISIT_OCCURRENCE:

> Quitting from lines 834-835 (STEP4to5-VISIT_OCCURRENCE.v10.16_05_2021.Rmd) 
> Error in `[.data.table`(dt, complete.cases(meaning), lapply(.SD, FUN = function(x) sum(complete.cases(x))),  : 
>   Some items of .SDcols are not column names: [speciality_of_visit]
> invalid option "error"

We modified the scripts from line 51 changing the 'speciality_of_visit' for 'specialty_of_visit' a variable we have in VISIT_OCCURRENCE table.

```
total_var<-as.data.table(cbind(table_name="VISIT_OCCURRENCE", 
        variable_name=c("person_id", "visit_occurrence_id", "visit_start_date","visit_end_date", 
                        "specialty_of_visit",
                        # "speciality_of_visit",
                        "speciality_of_visit_vocabulary","status_at_discharge",
                        "status_at_discharge_vocabulary", "meaning_of_visit", "origin_of_visit")))

```

**Comment by anallg** [comment]
We have the same problem but I´ve modify the name of the columns in visit file.

**Comment by acidroyo-UMCU** [comment]
@DanOV and @anallg is the errors still going?

Do you still have the error?

I would suggest changing your database column names to the ones used in the testing instead of changing the code. This way, the code will run accordingly, otherwise you need to change in many other places of the code the names and might not be feasible.

Let me know.
Best,
Albert

**Comment by DanOV** [comment]
Hi @acidroyo-UMCU 
We will change the column names as suggested.

Thanks!
Dan

**Comment by anallg** [comment]
@acidroyo-UMCU
We also change the column names
